### ISSUE TITLE
No module 'environment_var'

### ISSUE THREAD

**Issue by tigran123** [nikolamilosevic86/local-genAI-search#5]
When trying to run `python3.12 api.py` I get the error:

```
$ python3.12 api.py 
Traceback (most recent call last):
  File "/home/tigran/python/ml/local-genAI-search/api.py", line 10, in <module>
    import environment_var
ModuleNotFoundError: No module named 'environment_var'
```

even though everything listed in `requirements.txt` seems to be installed.

**Comment by nikolamilosevic86** [comment]
Hello @tigran123 ,

This is on purpose, as this is a python file containing keys. You will need to create environment_var.py file, containing two things:
hf_token = "hf_your_hugging_face_key"
nvidia_key = "nvapi-your_nvidia_api_key"

You have also more details here: https://towardsdatascience.com/how-to-build-a-generative-search-engine-for-your-local-files-using-llama-3-399551786965

**Comment by tigran123** [comment]
Thank you, that makes perfect sense now!
